module Viewer.Tests.Stubs

let stubbedElasticResponse = 
  """
  {
     "took":88,
     "timed_out":false,
     "_shards":{
        "total":5,
        "successful":5,
        "failed":0
     },
     "hits":{
        "total":2,
        "max_score":1.0,
        "hits":[
           {
              "_index":"kb",
              "_type":"qs",
              "_id":"qs1_st1",
              "_score":1.0,
              "_source":{
                 "@context":[
  
                 ],
                 "@id":"http://ld.nice.org.uk/prov/entity#f178fc5:qualitystandards/qs1/st1/Statement.md",
                 "content":"http://raw/f178fc5:qualitystandards/qs1/st1/Statement.md",
                 "http://ld.nice.org.uk/ns/compilation#path":{
                    "@language":"en",
                    "@value":"qualitystandards/qs1/st1/Statement.md"
                 },
                 "http://ld.nice.org.uk/ns/compilation#wasDerivedFrom":{
                    "@id":"http://raw/f178fc5:qualitystandards/qs1/st1/Statement.md"
                 },
                 "serviceArea":[
                    "http://ld.nice.org.uk/ns/qualitystandard/servicearea#Community health care"
                 ],
                 "setting":[
                    "http://ld.nice.org.uk/ns/qualitystandard/setting#Community"
                 ],
                 "targetPopulation":"http://ld.nice.org.uk/ns/qualitystandard/conditiondisease#Dementia",
                 "alternateOf":"http://ld.nice.org.uk/artifacts/f178fc5/text/html/qualitystandards/qs1/st1/Statement.html",
                 "specializationOf":"http://ld.nice.org.uk/resource#5E436DF737755F0AC3E35FDB6D892A52D070BA55D578F4321BC2FA48B9642C2F",
                 "wasAttributedTo":"http://ld.nice.org.uk/prov/user#alison.desimone@nice.org.uk",
                 "wasGeneratedBy":"http://ld.nice.org.uk/prov/commit#f178fc5"
              }
           }
           {
              "_index":"kb",
              "_type":"qs",
              "_id":"qs1_st2",
              "_score":1.0,
              "_source":{
                 "@context":[
  
                 ],
                 "@id":"http://ld.nice.org.uk/prov/entity#f178fc5:qualitystandards/qs1/st2/Statement.md",
                 "content":"http://raw/f178fc5:qualitystandards/qs1/st2/Statement.md",
                 "http://ld.nice.org.uk/ns/compilation#path":{
                    "@language":"en",
                    "@value":"qualitystandards/qs1/st2/Statement.md"
                 },
                 "http://ld.nice.org.uk/ns/compilation#wasDerivedFrom":{
                    "@id":"http://raw/f178fc5:qualitystandards/qs1/st2/Statement.md"
                 },
                 "serviceArea":[
                    "http://ld.nice.org.uk/ns/qualitystandard/servicearea#Community health care"
                 ],
                 "setting":[
                    "http://ld.nice.org.uk/ns/qualitystandard/setting#Community"
                 ],
                 "targetPopulation":"http://ld.nice.org.uk/ns/qualitystandard/conditiondisease#Dementia",
                 "alternateOf":"http://ld.nice.org.uk/artifacts/f178fc5/text/html/qualitystandards/qs1/st2/Statement.html",
                 "specializationOf":"http://ld.nice.org.uk/resource#5E436DF737755F0AC3E35FDB6D892A52D070BA55D578F4321BC2FA48B9642C2B",
                 "wasAttributedTo":"http://ld.nice.org.uk/prov/user#alison.desimone@nice.org.uk",
                 "wasGeneratedBy":"http://ld.nice.org.uk/prov/commit#f178fc5"
              }
           }
        ]
     }
  }
  """
